export const htmlQuestions = [
    "What are the differences between Html4 and Html5?",
    "What are semantic tags in Html? Give me some examples.",
    "What is the purpose of article, div, section, nav, aside?",
    "Why will you use Meta tag?",
    "What is the difference between inline, inline-block and block?",
    "Difference between strong, bold, em, i?",
    "What are properties and attributes in Html?",
    "What is a Viewport?",
    "Have you used Audio and Video tags? How do they work?",
    "What is hyperlink in Html? What tag and attribute will you use for hyperlink?",
    "What is the difference between Html elements and tags?",
    "What is charset in Html? Why will you use it?",
    "What is the difference between span and div?",
    "What is the ‘class’ attribute in Html?",
    "How to include JavaScript code in Html?"
];

export const cssQuestions = [
    "What is flex layout? Difference between flex and grid layout?",
    "Explain CSS position property? Difference between absolute position and relative position?",
    "What is a box model? What are the different elements of a box model?",
    "What is a hover effect? What are the purposes of active class?",
    "What is Pseudo-class? Give some example.",
    "What are the different types of CSS selectors? Difference between class selector and id selector?",
    "What is CSS specificity?",
    "What is CSS Preprocessor? What are some benefits of Sass?",
    "What is Pseudo-element? Give some example.",
    "How will you use media query to make a website responsive?",
    "Difference between transition and transformation?",
    "How will you horizontally and vertically center a div inside a div?",
    "What is z-index?",
    "Difference between visibility:hidden and display:none?"
];

export const jsQuestion = [
    "How does JavaScript work?",
    "How does JavaScript code is executed in the browser?",
    "Difference between '==' and '==='? ",
    "What is a callback function?",
    "How will you return more than one value from a function?",
    "What is bind, call and apply method?",
    "What is a closure? How does it work?",
    "What does the 'this' keyword indicate in JavaScript?",
    "What is event bubbling?",
    "What is hoisting?",
    "What is a recursive function?",
    "Difference between undefined and null?",
    "What are the different data types in JavaScript?",
    "What is DOM?",
    "Is JavaScript a static type or a dynamic type?",
    "What is ES6 and what are its features?",
    "What are the differences between var, let and const?",
    "Why we use default parameters?",
    "What is spread operator? And How does it work?",
    "Difference between class and object?",
    "What is a Prototype chain?",
    "Explain call by value vs call by reference?",
    "What is scope in JavaScript?",
    "What is a Higher-order function?",
    "What is an API? What is REST API? Advantages of REST API?",
    "Difference between GET and POST method?",
    "Difference between PUT and PATCH method?",
    "Difference between Local storage nad Session storage?",
    "What are cookies? And why will you use it?",
    "What is object-oriented programming?",
    "Difference between Array vs LinkedList?",
    "How will you debug a JavaScript application?"
];

export const reactQuestion = [
    "What is ReactJS? Advantages and Disadvantages of ReactJS",
    "Why will you select ReactJS / Why ReactJS is so popular?",
    "What is Virtual dom? difference between virtual dom and real dom?",
    "Differences between props and state?",
    "What is the purpose of useState? When and why will you use it?",
    "Difference between useState and useEffect?",
    "What is context API? How does it work?",
    "What is JSX? How does it work?",
    "Explain React component lifecycle.",
    "What is custom hook? How to create one?",
    "How will you optimize a ReactJS application?",
    "What is Pure component?",
    "How will you send data from a Child component to a Parent component?",
    "What is the best way to send 4 or more props to a children component?",
    "What is Redux? And What is the purpose of Redux?",
    "What is React Native?",
    "What are Higher order components? Give example.",
    "Is there any reason to return something from a useEffect hook?",
    "What are the different ways to manage state in a React application?",
    "Why do we inject dependency array inside the useEffect hook?",
    "How will you prevent re-render in React application?",
    "Does React perform one-way data binding or two-way data binding?",
    "Why should we not update the state directly in a React component?",
    "How to pass a parameter to an event handler in React component?",
    "What are Fragments in React?",
    "Difference between useEffect and useMemo?"
];

export const nodeMongoQuestion = [
    "What is Node.js?",
    "Difference between Node.js and JavaScript?",
    "Is Node.js single threaded or multi threaded?",
    "Is Node.js blocking or non-blocking?",
    "What is Npm?",
    "What is the purpose of database?",
    "Difference between SQL and No-SQL? Which is more used and why?",
    "Why are Node.js and MongoDB mostly used with React instead of MySQL?",
    "What do you know about database design and database schema design?",
    "What will you do if your server-side crashes?",
    "How does API work?",
    "What is CURD?",
    "How will you secure an API?",
    "What is Mongoose? How does it work?",
    "What is Webpack?"
];
